env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
rules:
  valid-jsdoc: off
  padded-blocks: off
  array-bracket-spacing: off
  camelcase: off
  max-len:
    - warn
    - 150
